server:
  port: 8080

spring:
  datasource:
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 500
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
     change-log: classpath:db/changelog/db.changelog-master.xml
     enabled: false
     drop-first: false
# example values
#logging.level.org.springframework.web: TRACE

indexing-settings:
  sites:
    #- url: https://lenta.ru/
    #  name: Лента.ру
    #- url: https://skillbox.ru
    #  name: Skillbox
    - url: https://playback.ru/
      name: PlayBack.Ru
    - url: https://nopaper.ru/
      name: NoPaper.ru
    #- url: http://cimus.biz
    #  name: DOM
    - url: https://exotic-zoo.ru
      name: DOMIK

connection-settings:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0 Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41
  referrer: http://google.com
  timeout: 550