server:
  port: 8080

spring:
  datasource:
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&reWriteBatchedInserts=true
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true

      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
     change-log: classpath:db/changelog/db.changelog-master.xml
     enabled: true
     drop-first: false

  output:
    ansi:
      enabled: ALWAYS

indexing-settings:
  sites:
    #- url: https://playback.ru/
    #  name: PlayBack.Ru
    #- url: https://nopaper.ru/
    #  name: NoPaper.ru
    - url:  https://nikoartgallery.com/
      name: Art gallery
    - url: https://et-cetera.ru/mobile/
      name: Theatre Et Cetera
    #- url: https://ipfran.ru/
    #  name: IPF RAN
    - url: https://dombulgakova.ru/
      name: Dom Bulgakova
    #- url: https://ya.ru/
    #  name: Yandex

connection-settings:
  #userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 YaBrowser/24.12.0.0 Safari/537.36
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0
  #referrer: http://localhost
  referrer: SearchBot
  timeout: 550

exceptions:
  lemmaExceptions[0]: СОЮЗ
  lemmaExceptions[1]: МЕЖД
  lemmaExceptions[2]: ПРЕДЛ
  lemmaExceptions[3]: ЧАСТ

  fileExtensions[0]: .png
  fileExtensions[1]: .jpg
  fileExtensions[2]: .pdf
  fileExtensions[3]: .mp4
  fileExtensions[4]: .jpeg

  #pathContaining[0]: '#'
  pathContaining[1]: '?'