server:
  port: 8080

spring:
  datasource:
    username: root
    #username: postgres
    password: pass
    #url: jdbc:postgresql://localhost:5432/searchengine
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&reWriteBatchedInserts=true
    #driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true

      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
     change-log: classpath:db/changelog/db.changelog-master.xml
     enabled: true
     drop-first: false

  output:
    ansi:
      enabled: ALWAYS
# example values
#logginglevel.org.springframework.web: TRACE

indexing-settings:
  sites:
    #- url: https://playback.ru/
    #  name: PlayBack.Ru
    - url: https://nopaper.ru/
      name: NoPaper.ru
    #- url:  https://nikoartgallery.com/
    #  name: Art gallery
    - url: https://et-cetera.ru/mobile/
      name: Theatre Et Cetera
    - url: https://ipfran.ru/
      name: IPF RAN
    #- url: https://dombulgakova.ru/
    #  name: Dom Bulgakova

connection-settings:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0 Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41
  referrer: http://google.com
  timeout: 550

#logging:
#  level:
#    root: INFO
#    searchengine: DEBUG
#    org.springframework.web: ERROR
    # Output to a file named application.log.
#  file:
#    name: application.log